kill subscriber process when desktop is removed
phenax/bsp-layout pull request #36
Opened 2021-10-19 03:12 UTC by no3m

change the way kill_layout gets called... desktop options in remove_listener have to be cleared before calling kill_layout, otherwise if remove_listener is called by the subscriber process on desktop_remove event, it will kill itself before the options are cleared.

added 'did' (desktop id) option... once desktop_remove event is triggered, get_desktop_name_from_id is useless since desktop doesn't exist anymore.

2022-06-11 16:18 UTC, phenax requested changes
Sorry for the delay. There's some changes needed here. Let me know if you'll be able to make those changes, if not I'll pick this up when I can and merge it in.

2022-06-11 16:18 UTC, phenax commented on src/layout.sh
> +  desktop_id=$(bspc query -D -d "$selected_desktop");
nit: this can be a function inside desktop.sh

2022-06-11 16:18 UTC, phenax commented on src/layout.sh
>  kill_layout() {
`kill_layout`'s purpose is to kill the layout of a desktop. It doesn't make sense for it to accept a pid. Maybe we can have 2 functions `kill_layout` and `kill_process`

2022-06-16 17:18 UTC, a2n-s commented
@phenax, in case @no3m does not respond, would you like me to try to fix the requests you made on the commit? :yum:

2022-07-09 08:43 UTC, a2n-s commented
Hi @no3m :wave: :yum: 

as this PR has ben stale for almost 8 months now, we've decided with @phenax to move the changes to [a2n-s/kill-subscriber-process-when-desktop-is-removed](https://github.com/a2n-s/bsp-layout/tree/kill-subscriber-process-when-desktop-is-removed) and apply the requested changes there :+1:

hope you'll understand :wink:

2022-07-09 08:43 UTC, closed without merging